### ISSUE TITLE
NHSNumberVerificationStatus is been created as the wrong data type

### ISSUE THREAD

**Issue by ymor** [clarotech/CCLibFoundation#1]
The CCSetNHSNumber extension with NHSNumberVerificationStatus  is currently creating a "Coding" data type for the verification status, instead of a "Codeable Concept" data type.

https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-NHSNumberVerificationStatus-1

**Comment by clarotech** [comment]
@ymor Thanks for pointing that out. Looking at https://fhir.hl7.org.uk/STU3/StructureDefinition/Extension-CareConnect-NHSNumberVerificationStatus-1 you are quite correct. I'll get that fixed.

**Comment by clarotech** [comment]
Fixed and new NuGet released, with some additional functionality as well.
